backend:
  name: github
  branch: master
  squash_merges: true
  repo: uzh-bf/gbl-web
  base_url: https://gbl-web.vercel.app/
  auth_endpoint: api/auth

local_backend: true

publish_mode: editorial_workflow
media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: pages
    label: Pages
    folder: content/pages/
    extension: mdx
    format: frontmatter
    identifier_field: slug
    fields:
      - label: Slug
        name: slug
        widget: string

      - label: Title
        name: title
        widget: string

      - label: Body
        name: body
        widget: markdown

  - name: games
    label: Games
    folder: content/games/
    extension: mdx
    format: frontmatter
    create: true
    identifier_field: slug
    fields:
      - label: Slug
        name: slug
        widget: string

      - label: Thumbnail
        name: thumbnail
        widget: image

      - label: Title
        name: title
        widget: string

      - label: Subtitle
        name: subtitle
        widget: string

      - label: Content
        name: body
        widget: markdown

      - label: Learning Objectives
        name: objectives
        widget: list
        field:
          label: Name
          name: Name
          widget: string

      - label: Usage Scenarios
        name: scenarios
        widget: list
        field:
          label: Name
          name: Name
          widget: string

      - label: Content Language(s)
        name: language
        widget: select
        options: ['de', 'en', 'fr', 'it']
        multiple: true

      - label: Keywords
        name: keywords
        widget: list

      - label: Imprint
        name: imprint
        widget: markdown

      - label: Contact
        name: contact
        widget: markdown
