backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'games'
    label: 'Games'
    folder: '_games'
    create: true
