backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: pages
    label: Pages
    folder: content/pages/
    extension: mdx
    format: frontmatter
    identifier_field: slug
    fields:
      - { label: Slug, name: slug, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
      - label: Cats
        name: cats
        widget: list
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Description, name: description, widget: text }

  - name: games
    label: Games
    folder: content/games/
    extension: mdx
    format: frontmatter
    create: true
    identifier_field: slug
    fields:
      - { label: Slug, name: slug, widget: string }
      - { label: Thumbnail, name: thumbnail, widget: image }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string }
      - { label: Content, name: body, widget: markdown }
      - { label: Learning Objectives, name: objectives, widget: list }
